export const ENTITY_IMPORT_MAX_FILE_SIZE_BYTES = 5 * 1024 * 1024;

export const ENTITY_REFERENCE_GENERATION = {
  MODEL: 'gpt-image-2',
  QUALITY: 'low',
  SIZE: '1024x1536',
  CANDIDATE_COUNT: 3,
} as const;

export const ENTITY_IMPORT_ANALYSIS_MODEL = 'gpt-4o';

export const ENTITY_REFERENCE_LIMITS = {
  MIN_CONFIRM_COUNT: 1,
  MAX_CONFIRM_COUNT: 3,
  MAX_PROMPT_SUPPLEMENT_LENGTH: 2000,
  MAX_REFERENCE_ID_LENGTH: 200,
} as const;
