import { CREDIT_COSTS } from './credits.js';

export const THINKING_MODE_THRESHOLDS = {
  MAX_ENTITIES_FOR_STANDARD: 4,
  MAX_PANELS_FOR_STANDARD: 8,
} as const;

export const PAGE_GENERATION_QUALITY = {
  INITIAL: 'medium',
  REGENERATE: 'high',
} as const;

export const PAGE_GENERATION_CREDIT_COSTS = {
  standard: CREDIT_COSTS.PAGE_GENERATION_STANDARD,
  thinking: CREDIT_COSTS.PAGE_GENERATION_THINKING,
  regenerate: CREDIT_COSTS.PAGE_REGENERATION,
} as const;

export const PAGE_PROMPT_COMPILER_OPENAI_MODEL = 'gpt-5.4-mini';
export const PAGE_PROMPT_COMPILER_MAX_TOKENS = 900;
export const PAGE_PROMPT_COMPILER_VERSION = 'page_prompt_v2';

export const STYLE_REFERENCE_COMPILER_OPENAI_MODEL = 'gpt-5.4-mini';
export const STYLE_REFERENCE_COMPILER_MAX_TOKENS = 500;
export const STYLE_REFERENCE_COMPILER_VERSION = 'style_ref_v3';

export const PAGE_AUTOFILL_COMPILER_OPENAI_MODEL = 'gpt-5.2';
export const PAGE_AUTOFILL_COMPILER_MAX_TOKENS = 1200;
export const PAGE_AUTOFILL_COMPILER_VERSION = 'page_autofill_v2';

export const EPISODE_PAGE_PLAN_COMPILER_OPENAI_MODEL = 'gpt-5.2';
export const EPISODE_PAGE_PLAN_COMPILER_MAX_TOKENS = 12000;
export const EPISODE_PAGE_PLAN_COMPILER_VERSION = 'episode_page_plan_v2';
