export const MAX_EPISODE_STARTING_ENTITY_STATES = 100;
export const MAX_EPISODE_STATE_TRANSITIONS = 512;
export const MAX_EPISODE_STATE_SOURCE_QUOTE_CHARS = 300;
export const MAX_EPISODE_STATE_JOB_BLOCKER_CANDIDATES = 20;
export const MAX_EPISODE_STATE_JOB_BLOCKER_DESCRIPTION_CHARS = 500;
