import {randomUUID} from 'node:crypto';
import {Pool,type QueryResultRow} from 'pg';
import {afterAll,beforeAll,describe,expect,it} from 'vitest';
import type {DatabaseClient,TransactionRunner} from '../../src/lib/db.js';
import {runPendingMigrations} from '../../src/lib/migrations.js';
import {PostgresStorePurchaseRepository} from '../../src/repositories/StorePurchaseRepository.js';
import {PostgresCreditRepository} from '../../src/repositories/CreditRepository.js';
import {MobileStorePurchaseService} from '../../src/services/billing/MobileStorePurchaseService.js';
import {createGooglePlayObfuscatedAccountId,createStoreProductCatalog,type VerifiedStorePurchase} from '../../src/domain/storePurchase.js';
import {withPostgresTestMigrationLock} from './postgresTestMigrationLock.js';
const dbDescribe=process.env.APP_ENV==='test'&&process.env.DATABASE_URL?describe:describe.skip;
const secret='test-only-secret-32-characters-long';
dbDescribe('production store behavior on candidate schema',()=>{
 let admin:Pool,pool:Pool,database:DatabaseClient&TransactionRunner;
 const schema=`store_compatibility_${process.pid}_${Date.now()}`;
 beforeAll(async()=>{admin=new Pool({connectionString:process.env.DATABASE_URL});await admin.query(`CREATE SCHEMA ${schema}`);pool=new Pool({connectionString:process.env.DATABASE_URL,options:`-c search_path=${schema},public`,max:12});database=testDatabase(pool);await withPostgresTestMigrationLock(admin,()=>runPendingMigrations(database));},120000);
 afterAll(async()=>{if(pool)await pool.end();if(admin){await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}});
 async function fixture(){const id=randomUUID();await pool.query('INSERT INTO users(id,supabase_id,email) VALUES($1,$2,$3)',[id,id,`${id}@example.invalid`]);await pool.query('INSERT INTO credit_balances(user_id,purchased_credits) VALUES($1,7)',[id]);let verified:VerifiedStorePurchase={store:'google',environment:'production',productId:'standard',externalPurchaseId:`token-${id}`,linkedExternalPurchaseId:null,transactionId:`order-${id}`,eventId:null,state:'active',observedAt:new Date(),expiresAt:new Date(Date.now()+30*86400000),autoRenewEnabled:true,renewalProductId:'premium',accountBinding:createGooglePlayObfuscatedAccountId(secret,id),isTestPurchase:false,providerEventType:'google.play.subscription',providerCompletion:'none'};const repo=new PostgresStorePurchaseRepository(database,database);const service=new MobileStorePurchaseService({storePurchaseRepository:repo,creditRepository:new PostgresCreditRepository(database,database),productCatalog:createStoreProductCatalog([{store:'google',productId:'standard',kind:'subscription',planCode:'standard'},{store:'google',productId:'premium',kind:'subscription',planCode:'premium'}]),appleVerifier:{verifyTransaction:async()=>{throw new Error('unused');},verifyNotification:async()=>null},googleVerifier:{verifyPurchase:async()=>({...verified}),completePurchase:async()=>{}},identifierSecret:secret,allowAppleSandbox:false,allowGoogleTestPurchases:false,googlePackageName:'jp.lyra.test'});return {id,repo,service,get:()=>verified,set:(value:Partial<VerifiedStorePurchase>)=>{verified={...verified,...value};}};}
 it('retains scheduled plan through SQL roundtrip and changes current plan only on verified renewal',async()=>{const f=await fixture();const first=await f.service.verifyGooglePurchase({userId:f.id,purchaseToken:'unused'});expect(first).toMatchObject({planCode:'standard',scheduledPlanCode:'premium',creditsChanged:50});const stored=await pool.query('SELECT product_id,scheduled_product_id,scheduled_plan_code FROM mobile_store_purchases WHERE user_id=$1',[f.id]);expect(stored.rows[0]).toEqual({product_id:'standard',scheduled_product_id:'premium',scheduled_plan_code:'premium'});expect(await f.service.getPersonalSubscriptionSummary(f.id)).toMatchObject({planCode:'standard',scheduledPlanCode:'premium'});f.set({productId:'premium',renewalProductId:null,transactionId:`next-${f.id}`,observedAt:new Date(Date.now()+1000)});const results=await Promise.all([f.service.verifyGooglePurchase({userId:f.id,purchaseToken:'same'}),f.service.verifyGooglePurchase({userId:f.id,purchaseToken:'same'})]);expect(results.map(x=>x.creditsChanged).sort((a,b)=>a-b)).toEqual([0,175]);const balance=await pool.query('SELECT monthly_credits,purchased_credits FROM credit_balances WHERE user_id=$1',[f.id]);expect(balance.rows[0]).toEqual({monthly_credits:175,purchased_credits:7});expect((await pool.query('SELECT count(*)::int n FROM mobile_store_purchases WHERE user_id=$1',[f.id])).rows[0].n).toBe(1);expect(await f.service.getPersonalSubscriptionSummary(f.id)).toMatchObject({planCode:'premium',scheduledPlanCode:null});});
 it('malformed authenticated notifications are recorded once without raw data and no credit changes',async()=>{const f=await fixture();const input={messageId:`malformed-${f.id}`,data:'private-invalid-base64',publishTime:new Date()};await f.service.handleGoogleRtdn(input);await f.service.handleGoogleRtdn(input);const result=await pool.query("SELECT provider_event_type,state FROM mobile_store_purchase_events WHERE provider_event_type='google.invalid_notification'");expect(result.rows).toEqual([{provider_event_type:'google.invalid_notification',state:'failed'}]);expect((await pool.query('SELECT purchased_credits FROM credit_balances WHERE user_id=$1',[f.id])).rows[0].purchased_credits).toBe(7);});
 it('account deletion gate prevents later verified renewal from restoring credits',async()=>{const f=await fixture();await f.service.verifyGooglePurchase({userId:f.id,purchaseToken:'initial'});await pool.query("UPDATE users SET account_deletion_started_at=NOW(),plan_code='free' WHERE id=$1",[f.id]);await pool.query('UPDATE credit_balances SET monthly_credits=0,purchased_credits=0 WHERE user_id=$1',[f.id]);f.set({productId:'premium',renewalProductId:null,transactionId:`late-${f.id}`,observedAt:new Date(Date.now()+1000)});const result=await f.service.verifyGooglePurchase({userId:f.id,purchaseToken:'late'});expect(result.creditsChanged).toBe(0);expect((await pool.query('SELECT plan_code FROM users WHERE id=$1',[f.id])).rows[0].plan_code).toBe('free');expect((await pool.query('SELECT monthly_credits,purchased_credits FROM credit_balances WHERE user_id=$1',[f.id])).rows[0]).toEqual({monthly_credits:0,purchased_credits:0});});
});
function testDatabase(pool:Pool):DatabaseClient&TransactionRunner{return {query:async<Row extends QueryResultRow=QueryResultRow>(text:string,values?:unknown[])=>pool.query<Row>(text,values),transaction:async<T>(fn:(db:DatabaseClient)=>Promise<T>)=>{const c=await pool.connect();try{await c.query('BEGIN');const result=await fn({query:async<Row extends QueryResultRow=QueryResultRow>(text:string,values?:unknown[])=>c.query<Row>(text,values)});await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}};}
