import {randomUUID} from 'node:crypto';
import {Pool,type QueryResultRow} from 'pg';
import {afterAll,beforeAll,describe,expect,it} from 'vitest';
import type {DatabaseClient,TransactionRunner} from '../../src/lib/db.js';
import {runPendingMigrations} from '../../src/lib/migrations.js';
import {PostgresPushNotificationDeliveryRepository} from '../../src/repositories/PushNotificationDeliveryRepository.js';
import {PostgresPushTokenRepository} from '../../src/repositories/PushTokenRepository.js';
import {withPostgresTestMigrationLock} from './postgresTestMigrationLock.js';
import { throwingRejectionOf } from './asyncPostgresAssertions.js';
const dbDescribe=process.env.APP_ENV==='test'&&process.env.DATABASE_URL?describe:describe.skip;
dbDescribe('production push delivery on guarded candidate schema',()=>{
 let admin:Pool,pool:Pool,database:DatabaseClient&TransactionRunner,repo:PostgresPushNotificationDeliveryRepository;
 const schema=`push_delivery_compat_${process.pid}_${Date.now()}`;
 beforeAll(async()=>{admin=new Pool({connectionString:process.env.DATABASE_URL});await admin.query(`CREATE SCHEMA ${schema}`);pool=new Pool({connectionString:process.env.DATABASE_URL,options:`-c search_path=${schema},public`,max:12});database=testDatabase(pool);repo=new PostgresPushNotificationDeliveryRepository(database,database);await withPostgresTestMigrationLock(admin,()=>runPendingMigrations(database));},120000);
 afterAll(async()=>{if(pool)await pool.end();if(admin){await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}});
 async function fixture(){const userId=randomUUID(),workId=randomUUID(),chapterId=randomUUID(),episodeId=randomUUID(),pageId=randomUUID(),jobId=randomUUID(),tokenId=randomUUID(),outboxId=randomUUID(),deliveryId=randomUUID();await pool.query('INSERT INTO users(id,supabase_id,email) VALUES($1,$2,$3)',[userId,userId,`${userId}@example.invalid`]);await pool.query("INSERT INTO works(id,user_id,title) VALUES($1,$2,'Push fixture')",[workId,userId]);await pool.query('INSERT INTO chapters(id,work_id,"order") VALUES($1,$2,1)',[chapterId,workId]);await pool.query('INSERT INTO episodes(id,chapter_id,"order") VALUES($1,$2,1)',[episodeId,chapterId]);await pool.query("INSERT INTO pages(id,episode_id,page_number,status) VALUES($1,$2,1,'editing')",[pageId,episodeId]);await pool.query("INSERT INTO generation_jobs(id,user_id,job_type,status,generation_mode,credit_cost,params) VALUES($1,$2,'page_generate','completed','standard',0,$3::jsonb)",[jobId,userId,JSON.stringify({page_id:pageId})]);await pool.query("INSERT INTO mobile_push_tokens(id,user_id,installation_id,platform,locale,token_hash,token_ciphertext,encryption_key_id) VALUES($1,$2,$3,'android','ja',$4,$5,'test-v1')",[tokenId,userId,randomUUID(),tokenId.replaceAll('-','').repeat(2),`v1.${'b'.repeat(16)}.${'c'.repeat(40)}.${'d'.repeat(22)}`]);await pool.query("INSERT INTO mobile_push_notification_outbox(id,generation_job_id,user_id,terminal_status,generation_retry_count) VALUES($1,$2,$3,'completed',0)",[outboxId,jobId,userId]);await pool.query('INSERT INTO mobile_push_notification_deliveries(id,outbox_id,push_token_id) VALUES($1,$2,$3)',[deliveryId,outboxId,tokenId]);return {userId,workId,chapterId,episodeId,pageId,jobId,tokenId,outboxId,deliveryId};}
 it('claims a delivery once, returns only scoped navigation, and persists uppercase safe retry codes',async()=>{const f=await fixture();const groups=await Promise.all([repo.claimPending(1),repo.claimPending(1)]);const rows=groups.flat();expect(rows).toHaveLength(1);expect(rows[0].navigation).toMatchObject({job_id:f.jobId,page_id:f.pageId,target_tab:'Pages'});expect(await repo.isDeliveryCurrent(rows[0].deliveryId,rows[0].leaseToken)).toBe(true);await repo.markRetry(rows[0].deliveryId,rows[0].leaseToken,'provider_timeout',new Date(Date.now()+10000));expect((await pool.query('SELECT status,error_code,lease_token FROM mobile_push_notification_deliveries WHERE id=$1',[f.deliveryId])).rows[0]).toEqual({status:'pending',error_code:'PROVIDER_TIMEOUT',lease_token:null});await pool.query("UPDATE mobile_push_notification_deliveries SET status='canceled' WHERE id=$1",[f.deliveryId]);});
 it('revoked/deleted recipient or stale retry context cannot be dispatched',async()=>{for(const mode of ['deleted','retry'] as const){const f=await fixture();if(mode==='deleted')await pool.query('UPDATE users SET account_deletion_started_at=NOW() WHERE id=$1',[f.userId]);else await pool.query('UPDATE generation_jobs SET retry_count=1 WHERE id=$1',[f.jobId]);expect(await repo.claimPending(1)).toEqual([]);expect((await pool.query('SELECT status,error_code FROM mobile_push_notification_deliveries WHERE id=$1',[f.deliveryId])).rows[0]).toMatchObject({status:'dead',error_code:'MISSING_NAVIGATION_CONTEXT'});}});
 it('rechecks token ownership and lease just before delivery',async()=>{const f=await fixture();const [claimed]=await repo.claimPending(1);await pool.query('DELETE FROM mobile_push_tokens WHERE id=$1',[f.tokenId]);expect(await repo.isDeliveryCurrent(f.deliveryId,claimed.leaseToken)).toBe(false);expect(await repo.markSent(f.deliveryId,claimed.leaseToken)).toBe(false);expect((await pool.query('SELECT status FROM mobile_push_notification_deliveries WHERE id=$1',[f.deliveryId])).rows[0].status).toBe('canceled');});
 it('registration after deletion admission is rejected without any token insertion',async()=>{const f=await fixture();await pool.query("UPDATE mobile_push_notification_deliveries SET status='canceled' WHERE id=$1",[f.deliveryId]);await pool.query('UPDATE users SET account_deletion_started_at=NOW() WHERE id=$1',[f.userId]);const count=(await pool.query('SELECT count(*)::int n FROM mobile_push_tokens WHERE user_id=$1',[f.userId])).rows[0].n;expect(await throwingRejectionOf(new PostgresPushTokenRepository(database).upsertForUser({userId:f.userId,installationId:randomUUID(),platform:'android',locale:'ja',tokenHash:'a'.repeat(64),tokenCiphertext:`v1.${'b'.repeat(16)}.${'c'.repeat(40)}.${'d'.repeat(22)}`,encryptionKeyId:'test-v1'}))).toThrow('Account is unavailable');expect((await pool.query('SELECT count(*)::int n FROM mobile_push_tokens WHERE user_id=$1',[f.userId])).rows[0].n).toBe(count);});
});
function testDatabase(pool:Pool):DatabaseClient&TransactionRunner{return {query:async<Row extends QueryResultRow=QueryResultRow>(text:string,values?:unknown[])=>pool.query<Row>(text,values),transaction:async<T>(fn:(db:DatabaseClient)=>Promise<T>)=>{const c=await pool.connect();try{await c.query('BEGIN');const result=await fn({query:async<Row extends QueryResultRow=QueryResultRow>(text:string,values?:unknown[])=>c.query<Row>(text,values)});await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}};}
