import { describe,expect,it,vi } from 'vitest';
import { PageThumbnailService } from '../../../../src/services/page/PageThumbnailService.js';
const source=()=>({id:'page',updatedAt:new Date('2026-10-01T00:00:00Z'),generatedImage:{s3Key:'session/user/pages/page/job.png',cdnUrl:null,generationMode:'standard',generatedAt:'2026-10-01T00:00:00Z'}});
function fixture(){const page=source();const repository={findPageByIdAndUserId:vi.fn(async()=>page)};const loader={loadByS3Key:vi.fn(async()=>({imageData:Buffer.from('image'),mimeType:'image/png' as const}))};const renderer={render:vi.fn(async()=>({imageData:Buffer.from('thumb'),mimeType:'image/webp' as const}))};return {page,repository,loader,renderer,service:new PageThumbnailService(repository as never,loader,renderer)};}
describe('thumbnail delivery',()=>{
 it('revision取得は認可後に行い画像を読まずscopeと由来を含む',async()=>{const f=fixture();const revision=await f.service.getGeneratedImageThumbnailRevision('user','page');expect(f.loader.loadByS3Key).not.toHaveBeenCalled();expect(await f.service.getGeneratedImageThumbnailRevision('user','page','org')).not.toBe(revision);const thumb=await f.service.getGeneratedImageThumbnail('user','page');expect(thumb).toMatchObject({revision,mimeType:'image/webp'});});
 it.each(['hy4-preview','unknown'])('制限付き%sはETag照合前でもbytes取得前でも拒否する',async(imageModel)=>{const f=fixture();Object.assign(f.page.generatedImage,{imageModel});await expect(f.service.getGeneratedImageThumbnailRevision('user','page')).rejects.toMatchObject({statusCode:403});await expect(f.service.getGeneratedImageThumbnail('user','page')).rejects.toMatchObject({statusCode:403});expect(f.loader.loadByS3Key).not.toHaveBeenCalled();expect(f.renderer.render).not.toHaveBeenCalled();});
 it('別ownerのキーは画像を読まず拒否する',async()=>{const f=fixture();f.page.generatedImage.s3Key='session/other/pages/page/job.png';await expect(f.service.getGeneratedImageThumbnail('user','page')).rejects.toThrow();expect(f.loader.loadByS3Key).not.toHaveBeenCalled();});
});
