import assert from 'node:assert/strict';
import test from 'node:test';
import { createStageDatabaseDrainInvokePort } from './stage-database-drain-invoke-port.mjs';
const arn='arn:aws:lambda:ap-northeast-1:452284481392:function:lyra-staging-20261003-database-drain-proof:1';
const now='2026-10-09T15:00:00.000Z', safe='2026-10-09T14:59:00.000Z';
const proof=()=>({kind:'lyra-staging-db-drain-proof',schemaVersion:1,stageId:'lyra-staging-20261003',clusterId:'lyra-staging-20261003-cluster',databaseId:'lyra-staging-20261003-db',observedAtUtc:now,counters:{activeGenerationJobs:0,pendingGenerationDispatches:0,activeEpisodeExportJobs:0,pendingEpisodeExportOutbox:0,activeAccountDeletionRequests:0,pendingPushDeliveries:0,pendingCreditRefunds:0}});
function harness(response={StatusCode:200,ExecutedVersion:'1',Payload:Buffer.from(JSON.stringify({ok:true,proof:proof()}))}) { const calls=[]; const port=createStageDatabaseDrainInvokePort({functionArn:arn,lambda:{send:async(c,o)=>{calls.push({c,o});return response;}},invokeCommand:x=>x}); return {port,calls}; }
test('固定versionへ空入力を送りcleanup済みの新しいcounter証明を受け取る',async()=>{const {port,calls}=harness(); assert.deepEqual(await port.collect({nowUtc:now,safePointAtUtc:safe}),proof()); assert.equal(calls.length,1); assert.equal(calls[0].c.FunctionName,arn); assert.equal(calls[0].c.InvocationType,'RequestResponse'); assert.equal(Buffer.from(calls[0].c.Payload).toString(),'{}'); assert.equal(calls[0].c.LogType,undefined); assert.ok(calls[0].o.abortSignal instanceof AbortSignal);});
test('処理中counterは有効な証明として返すが停止可能を示さない',async()=>{const p=proof(); p.counters.activeGenerationJobs=1; const {port}=harness({StatusCode:200,ExecutedVersion:'1',Payload:Buffer.from(JSON.stringify({ok:true,proof:p}))}); assert.equal((await port.collect({nowUtc:now,safePointAtUtc:safe})).counters.activeGenerationJobs,1);});
for(const bad of [arn.replace(':1',':$LATEST'),arn.replace(':1',':01'),arn.slice(0,-2),arn.replace('452284481392','000000000000'),arn.replace('ap-northeast-1','us-east-1'),arn.replace('database-drain-proof','api')]) test('対象外または固定されないversionを拒否する '+bad.slice(-20),()=>{assert.throws(()=>createStageDatabaseDrainInvokePort({functionArn:bad,lambda:{send(){}},invokeCommand:x=>x}));});
for(const [name,extra] of [['非200',{StatusCode:202}],['違うversion',{ExecutedVersion:'2'}],['Lambda失敗',{FunctionError:'Unhandled'}],['巨大payload',{Payload:Buffer.alloc(2049)}],['不正JSON',{Payload:Buffer.from('{')}],['executor失敗',{Payload:Buffer.from(JSON.stringify({ok:false,error:'DATABASE_DRAIN_EXECUTOR_FAILED'}))}],['余分なwrapper',{Payload:Buffer.from(JSON.stringify({ok:true,proof:proof(),secret:'x'}))}]]) test(name+'を証明として採用しない',async()=>{const {port}=harness({StatusCode:200,ExecutedVersion:'1',Payload:Buffer.from(JSON.stringify({ok:true,proof:proof()})),...extra}); await assert.rejects(port.collect({nowUtc:now,safePointAtUtc:safe}));});
for(const [name,modify] of [['別DB',p=>{p.databaseId='lyra-prod-db';}],['counter不足',p=>{delete p.counters.pendingCreditRefunds;}],['負数',p=>{p.counters.pendingCreditRefunds=-1;}],['古い時刻',p=>{p.observedAtUtc='2026-10-09T14:50:00.000Z';}],['未来時刻',p=>{p.observedAtUtc='2026-10-09T15:01:00.000Z';}],['safe point前',p=>{p.observedAtUtc='2026-10-09T14:58:00.000Z';}]]) test(name+'の証明を拒否する',async()=>{const p=proof();modify(p);const {port}=harness({StatusCode:200,ExecutedVersion:'1',Payload:Buffer.from(JSON.stringify({ok:true,proof:p}))});await assert.rejects(port.collect({nowUtc:now,safePointAtUtc:safe}));});
test('通信失敗を安全な固定codeへ変換する',async()=>{const port=createStageDatabaseDrainInvokePort({functionArn:arn,lambda:{send:async()=>{throw Error('private-password');}},invokeCommand:x=>x}); await assert.rejects(port.collect({nowUtc:now,safePointAtUtc:safe}), e=>e.message==='DATABASE_DRAIN_INVOKE_FAILED'&&!e.message.includes('private'));});
test('不正なsafe pointは外部へ送る前に拒否する',async()=>{const {port,calls}=harness();await assert.rejects(port.collect({nowUtc:now,safePointAtUtc:'bad'}));assert.equal(calls.length,0);});
