import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import test from 'node:test';
import { createHandler, executeDatabaseDrain, DATABASE_DRAIN_EXECUTOR_QUERY } from './stage-database-drain-executor.mjs';
const cert='-----BEGIN CERTIFICATE-----x-----END CERTIFICATE-----';
const env={STAGE_ID:'lyra-staging-20261003',AWS_REGION:'ap-northeast-1',AWS_ACCOUNT_ID:'452284481392',DB_HOST:'lyra-staging-20261003-db.abc.ap-northeast-1.rds.amazonaws.com',DB_NAME:'lyrastaging',DB_USER:'lyra_stage_drain_reader',DB_PASSWORD:'a'.repeat(64),RDS_CA_FILE:'/var/task/rds-ca-rsa2048-g1.pem',RDS_CA_SHA256:createHash('sha256').update(cert).digest('hex')};
const row={observed_at:new Date('2026-10-09T15:00:00.000Z'),active_generation_jobs:'0',pending_generation_dispatches:'0',active_episode_export_jobs:'0',pending_episode_export_outbox:'0',active_account_deletion_requests:'0',pending_push_deliveries:'0',pending_credit_refunds:'0'};
test('empty input only runs fixed read-only query with TLS',async()=>{const calls=[];const proof=await executeDatabaseDrain({event:{},env,readCaFile:async()=>cert,createClient:o=>({connect:async()=>calls.push(['connect',o]),query:async q=>(calls.push(q),q===DATABASE_DRAIN_EXECUTOR_QUERY?{rows:[row]}:{rows:[]}),end:async()=>calls.push('end')})});assert.equal(proof.schemaVersion,1);assert.deepEqual(calls.slice(1,4),['BEGIN READ ONLY',"SET LOCAL statement_timeout = '4000ms'",DATABASE_DRAIN_EXECUTOR_QUERY]);assert.equal(calls[0][1].ssl.rejectUnauthorized,true);});
test('input and internal errors are fail-closed and sanitized',async()=>{await assert.rejects(()=>executeDatabaseDrain({event:{sql:'x'},env,createClient:()=>null}),/INPUT_INVALID/);const out=await createHandler({env:{},createClient:()=>null,readCaFile:async()=>cert})({});assert.deepEqual(out,{ok:false,error:'DATABASE_DRAIN_EXECUTOR_FAILED'});});function fakeClient({ failAt, resultRow = row, calls = [] } = {}) { return { connect:async()=>{calls.push('connect');if(failAt==='connect')throw Error()}, query:async q=>{calls.push(q);if(failAt===q||failAt==='query')throw Error();return q===DATABASE_DRAIN_EXECUTOR_QUERY?{rows:[resultRow]}:{rows:[]}}, end:async()=>{calls.push('end');if(failAt==='end')throw Error()} }; }
for (const event of [{x:1},[],null]) test(`rejects nonempty executor event ${String(event)}`,async()=>{await assert.rejects(()=>executeDatabaseDrain({event,env,readCaFile:async()=>cert,createClient:()=>fakeClient()}),/INPUT_INVALID/);});
for (const [name,patch] of Object.entries({stage:{STAGE_ID:'x'},region:{AWS_REGION:'x'},account:{AWS_ACCOUNT_ID:'x'},host:{DB_HOST:'prod.example'},db:{DB_NAME:'prod'},user:{DB_USER:'root'},password:{DB_PASSWORD:'x'},caPath:{RDS_CA_FILE:'/tmp/x'},caHash:{RDS_CA_SHA256:'x'}})) test(`rejects invalid ${name} env`,async()=>{const out=await createHandler({env:{...env,...patch},readCaFile:async()=>cert,createClient:()=>fakeClient()})({});assert.equal(out.ok,false);});
test('rejects CA hash mismatch before connect',async()=>{let connected=false;const out=await createHandler({env:{...env,RDS_CA_SHA256:'b'.repeat(64)},readCaFile:async()=>cert,createClient:()=>({connect:async()=>{connected=true}})})({});assert.equal(out.ok,false);assert.equal(connected,false);});
for(const failure of ['connect','query',"ROLLBACK",'end']) test(`sanitizes ${failure} failure`,async()=>{const calls=[];const out=await createHandler({env,readCaFile:async()=>cert,createClient:()=>fakeClient({failAt:failure,calls})})({});assert.deepEqual(out,{ok:false,error:'DATABASE_DRAIN_EXECUTOR_FAILED'});});
for(const [name,bad] of Object.entries({counter:{...row,pending_push_deliveries:'-1'},clock:{...row,observed_at:'bad'}})) test(`rejects invalid ${name} row`,async()=>{const out=await createHandler({env,readCaFile:async()=>cert,createClient:()=>fakeClient({resultRow:bad})})({});assert.equal(out.ok,false);});
test('successful handler exports proof and always cleans up',async()=>{const calls=[];const out=await createHandler({env,readCaFile:async()=>cert,createClient:()=>fakeClient({calls})})({});assert.equal(out.ok,true);assert.ok(calls.includes('ROLLBACK'));assert.equal(calls.at(-1),'end');});
