import assert from 'node:assert/strict';import test from 'node:test';import{mkdir,mkdtemp,rm,writeFile}from'node:fs/promises';import{existsSync,readFileSync}from'node:fs';import{execFile}from'node:child_process';import path from 'node:path';import{pathToFileURL}from'node:url';import{promisify}from'node:util';
const template=JSON.parse(readFileSync(new URL('./runtime.json',import.meta.url),'utf8')),r=template.Resources;
test('Googleの期限処理を指定しない場合はサービスや周期実行を増やさない',()=>{for(const p of ['GoogleIdentityExpiryEnabled','GoogleIdentityExpiryScheduleEnabled'])assert.equal(template.Parameters[p]?.Default,'false');assert.equal(r.GoogleLinkExpiryTaskDefinition.Condition,'GoogleExpiryConfigured');assert.equal(r.GoogleLinkExpirySchedule.Properties.State['Fn::If'][2],'DISABLED');assert.equal(Object.hasOwn(r,'GoogleLinkExpiryService'),false);});
test('期限処理は検証secretをロードして検証DBだけで100件ずつ最大5回実行する',()=>{const task=r.GoogleLinkExpiryTaskDefinition.Properties,c=task.ContainerDefinitions[0];assert.equal(task.Cpu,'256');assert.equal(task.Memory,'512');assert.deepEqual(task.TaskRoleArn,{'Fn::GetAtt':['MigrationTaskRole','Arn']});assert.deepEqual(task.ExecutionRoleArn,{'Fn::GetAtt':['ExecutionRole','Arn']});assert.deepEqual(c.Command.slice(0,2),['/usr/local/bin/bun','-e']);const code=c.Command[2];assert.ok(code.indexOf('loadRuntimeSecretEnv')<code.indexOf('expireGoogleIdentityLinkChallenges'));assert.match(code,/APP_ENV/);assert.match(code,/rds\.amazonaws\.com/);assert.match(code,/limit:100/);assert.match(code,/batch<5/);assert.match(code,/closeDatabasePool/);assert.equal(c.Environment.some(e=>e.Name==='GOOGLE_LINK_CLIENT_SECRET'),false);});
test('Schedulerの信頼と起動権限は検証groupと専用taskと既存roleだけになる',()=>{const role=r.GoogleLinkExpirySchedulerRole.Properties;const trust=role.AssumeRolePolicyDocument.Statement[0];assert.equal(trust.Principal.Service,'scheduler.amazonaws.com');assert.deepEqual(trust.Condition.StringEquals['aws:SourceArn'],{'Fn::GetAtt':['GoogleLinkExpiryScheduleGroup','Arn']});assert.deepEqual(trust.Condition.StringEquals['aws:SourceAccount'],{Ref:'AWS::AccountId'});const statements=role.Policies[0].PolicyDocument.Statement;const run=statements.find(s=>s.Action==='ecs:RunTask');assert.deepEqual(run.Resource,{Ref:'GoogleLinkExpiryTaskDefinition'});assert.deepEqual(run.Condition.ArnEquals['ecs:cluster'],{Ref:'ClusterArn'});const pass=statements.find(s=>s.Action==='iam:PassRole');assert.deepEqual(pass.Resource,[{'Fn::GetAtt':['ExecutionRole','Arn']},{'Fn::GetAtt':['MigrationTaskRole','Arn']}]);assert.equal(pass.Condition.StringEquals['iam:PassedToService'],'ecs-tasks.amazonaws.com');});
test('周期実行の再試行と遅延時間は限定され失敗は専用DLQへ届く',()=>{const p=r.GoogleLinkExpirySchedule.Properties;assert.deepEqual(p.RetryPolicy,undefined);assert.deepEqual(p.Target.RetryPolicy,{MaximumEventAgeInSeconds:60,MaximumRetryAttempts:0});assert.deepEqual(p.Target.DeadLetterConfig.Arn,{'Fn::GetAtt':['GoogleLinkExpiryDlq','Arn']});assert.equal(p.ScheduleExpression,'rate(15 minutes)');assert.deepEqual(p.Target.EcsParameters.NetworkConfiguration.AwsvpcConfiguration.SecurityGroups,[{Ref:'WorkerSG'}]);assert.deepEqual(p.Target.EcsParameters.TaskDefinitionArn,{Ref:'GoogleLinkExpiryTaskDefinition'});});
test('Googleの周期処理は期限処理の有効化より先に有効化できない',()=>{assert.deepEqual(template.Rules.GoogleExpiryScheduleRequiresTask.Assertions[0].Assert,{'Fn::Equals':[{Ref:'GoogleIdentityExpiryEnabled'},'true']});assert.deepEqual(template.Rules.GoogleExpiryRequiresLinkGrant.Assertions[0].Assert,{'Fn::Equals':[{Ref:'GoogleIdentityLinkGrantEnabled'},'true']});});
test('期限処理は個人情報を出さず件数と失敗を監視する',()=>{const code=r.GoogleLinkExpiryTaskDefinition.Properties.ContainerDefinitions[0].Command[2];assert.match(code,/CleanupFailures/);assert.match(code,/CleanupAtLimit/);assert.match(code,/Lyra\/StagingGoogleAuth/);assert.equal(code.includes('console.error(error'),false);assert.equal(r.GoogleLinkExpiryFailureAlarm.Condition,'GoogleExpiryScheduleConfigured');assert.equal(r.GoogleLinkExpirySaturationAlarm.Properties.MetricName,'CleanupAtLimit');assert.equal(r.GoogleLinkExpiryDlqAlarm.Properties.MetricName,'ApproximateNumberOfMessagesVisible');});

// §10 offline execution proof: this fixture shadows only the task's relative
// imports, so no database or AWS SDK is loaded while the exact Command[2] runs.
const taskRoot=path.resolve('C:/Users/shogo/Lyra/.tmp/codex-completion-20261002/google-expiry-contract-fixtures');
const command=r.GoogleLinkExpiryTaskDefinition.Properties.ContainerDefinitions[0].Command[2],run=promisify(execFile);
function assertFixturePath(root){const resolved=path.resolve(root),base=path.resolve(taskRoot);assert.ok(resolved.startsWith(`${base}${path.sep}`),'fixture must remain below the intended task root');return resolved;}
async function fixture({counts,loaderHangs=false,loaderThrows=false}){await mkdir(taskRoot,{recursive:true});const root=assertFixturePath(await mkdtemp(path.join(taskRoot,'expiry-'))),dist=path.join(root,'dist');await writeFile(path.join(root,'clock.mjs'),"const clock=globalThis.setTimeout;globalThis.setTimeout=(fn,ms,...args)=>clock(fn,ms===120000?25:ms,...args);\n");await writeFile(path.join(root,'package.json'),'{"type":"module"}\n');await Promise.all([mkdir(path.join(dist,'src/lib'),{recursive:true}),mkdir(path.join(dist,'scripts'),{recursive:true})]);const marker=JSON.stringify(path.join(root,'db-started')),closed=JSON.stringify(path.join(root,'db-closed'));await writeFile(path.join(dist,'src/lib/runtimeSecretEnv.js'),loaderHangs?"export async function loadRuntimeSecretEnv(){await new Promise(()=>{});}" :loaderThrows?"throw new Error('private-loader-error fakepostgres://placeholder@lyra-staging-20261003-db.fake.ap-northeast-1.rds.amazonaws.com/lyra');\n":"const NativeUrl=globalThis.URL;globalThis.URL=class extends NativeUrl{constructor(value,...rest){super(String(value).replace(/^fakepostgres:/u,'postgresql:'),...rest);}};export async function loadRuntimeSecretEnv(){}\n");await writeFile(path.join(dist,'src/lib/db.js'),`import{writeFile}from'node:fs/promises';await writeFile(${marker},'started');export const db={};export async function closeDatabasePool(){await writeFile(${closed},'closed');}\n`);await writeFile(path.join(dist,'scripts/expireGoogleIdentityLinkChallenges.js'),`const counts=${JSON.stringify(counts)};let i=0;export async function expireGoogleIdentityLinkChallenges(){return{expired_exchange_material:counts[i++]??0};}\n`);return{root,marker:JSON.parse(marker),closed:JSON.parse(closed)};}
async function executeFixture(options){const f=await fixture(options);const databaseUrl=options.databaseUrl??'fakepostgres://placeholder@lyra-staging-20261003-db.fake.ap-northeast-1.rds.amazonaws.com/lyra';try{const result=await run(process.execPath,['--input-type=module',...(options.loaderHangs?['--import',pathToFileURL(path.join(f.root,'clock.mjs')).href]:[]),'-e',command],{cwd:f.root,timeout:5000,env:{...process.env,APP_ENV:'staging',LYRA_GOOGLE_EXPIRY_STAGE_PREFIX:'lyra-staging-20261003',DATABASE_URL:databaseUrl}}).then(value=>({code:0,...value}),error=>({code:error.code??1,stdout:error.stdout??'',stderr:error.stderr??''}));return{...result,fixture:f};}finally{/* caller asserts markers before safe cleanup */}}
async function cleanupFixture(root){const resolved=assertFixturePath(root);await rm(resolved,{recursive:true,force:true});}
test('期限処理は100件後40件で2回成功しpoolを閉じる',async()=>{const result=await executeFixture({counts:[100,40]});try{assert.equal(result.code,0);assert.equal((result.stdout.match(/"expired_exchange_material"/gu)??[]).length,2);assert.equal(existsSync(result.fixture.closed),true);}finally{await cleanupFixture(result.fixture.root);}});
test('期限処理は100件が5回続くと失敗EMFを出してpoolを閉じる',async()=>{const result=await executeFixture({counts:[100,100,100,100,100]});try{assert.equal(result.code,1);assert.match(result.stdout,/"CleanupFailures":1/u);assert.equal(existsSync(result.fixture.closed),true);}finally{await cleanupFixture(result.fixture.root);}});
test('secret loader失敗時はDB開始前に止まりprivate detailを出さない',async()=>{const result=await executeFixture({counts:[],loaderThrows:true});try{assert.equal(result.code,1);assert.equal(existsSync(result.fixture.marker),false);assert.equal(existsSync(result.fixture.closed),false);assert.equal(`${result.stdout}${result.stderr}`.includes('private-loader-error'),false);assert.equal(`${result.stdout}${result.stderr}`.includes('fakepostgres://'),false);}finally{await cleanupFixture(result.fixture.root);}});
test('loader成功後もproduction DB hostを拒否してDB開始前に止まりhostを出さない',async()=>{const productionHost='production-db.private.ap-northeast-1.rds.amazonaws.com';const result=await executeFixture({counts:[],databaseUrl:`fakepostgres://placeholder@${productionHost}/lyra`});try{assert.equal(result.code,1);assert.equal(existsSync(result.fixture.marker),false);assert.equal(existsSync(result.fixture.closed),false);assert.equal(`${result.stdout}${result.stderr}`.includes(productionHost),false);}finally{await cleanupFixture(result.fixture.root);}});

test('Schedulerのroleには専用の限定boundaryが付く',()=>{assert.deepEqual(r.GoogleLinkExpirySchedulerRole.Properties.PermissionsBoundary,{Ref:'GoogleLinkExpirySchedulerBoundary'});assert.equal(r.GoogleLinkExpirySchedulerBoundary.Condition,'GoogleExpiryConfigured');assert.deepEqual(r.GoogleLinkExpirySchedulerBoundary.Properties.PolicyDocument,r.GoogleLinkExpirySchedulerRole.Properties.Policies[0].PolicyDocument);});
test('Google期限処理を他の検証prefixへ適用しない',()=>{assert.deepEqual(template.Rules.GoogleExpiryRequiresExactStage.Assertions[0].Assert,{'Fn::Equals':[{Ref:'ResourcePrefix'},'lyra-staging-20261003']});});
test('secret読取が停止しても期限処理は固定deadlineで失敗する',async()=>{const result=await executeFixture({counts:[],loaderHangs:true});try{assert.equal(result.code,1);assert.equal(existsSync(result.fixture.marker),false);assert.match(result.stdout,/"CleanupFailures":1/u);assert.equal(`${result.stdout}${result.stderr}`.includes('private-loader-error'),false);}finally{await cleanupFixture(result.fixture.root);}});

// AWS actual CREATE_CHANGESET rejected the lowercase ECS API property here.
test('SchedulerのCFN設定が正規のnetwork構造と解決可能な専用groupを使う', () => {
  const schedule = template.Resources.GoogleLinkExpirySchedule;
  assert.deepEqual(schedule.Properties.GroupName, { 'Fn::Sub': '${ResourcePrefix}-google-auth' });
  assert.equal(schedule.DependsOn, 'GoogleLinkExpiryScheduleGroup');
  assert.deepEqual(schedule.Properties.Target.EcsParameters.NetworkConfiguration, {
    AwsvpcConfiguration: {
      AssignPublicIp: 'ENABLED',
      Subnets: [{ Ref: 'PublicSubnetAId' }, { Ref: 'PublicSubnetCId' }],
      SecurityGroups: [{ Ref: 'WorkerSG' }],
    },
  });
});

test('Schedulerの終了日時はAWS CFNが受理するミリ秒付きのUTC形式になる', () => {
  assert.equal(template.Resources.GoogleLinkExpirySchedule.Properties.EndDate, '2026-10-10T00:00:00.000Z');
});

test('専用groupのSchedule ARNはCFNのdefault group読取を使わず正しい所有範囲になる', () => {
  assert.deepEqual(template.Outputs.GoogleLinkExpiryScheduleArn.Value, { 'Fn::Sub': 'arn:${AWS::Partition}:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/${ResourcePrefix}-google-auth/${ResourcePrefix}-google-link-expiry' });
  const attributes=[];
  function visit(value) { if (!value || typeof value !== 'object') return; if (Object.hasOwn(value,'Fn::GetAtt')) attributes.push(value['Fn::GetAtt']); for (const child of Object.values(value)) visit(child); }
  visit(template);
  assert.equal(attributes.some(value => Array.isArray(value) ? value[0] === 'GoogleLinkExpirySchedule' : String(value).startsWith('GoogleLinkExpirySchedule.')), false);
});
