import { Hono, type MiddlewareHandler } from 'hono';
import { describe, expect, it, vi } from 'vitest';
import { createGoogleIdentityLinkRoutes } from '../../../src/routes/googleIdentityLinks.js';
import { errorHandler } from '../../../src/middleware/errorHandler.js';
import type { AppEnv } from '../../../src/types/app.js';
const id = '11111111-1111-4111-8111-111111111111';
const user = { id, supabaseId: 'native', email: 'owner@example.com', displayName: null, planCode: 'free' };
const noOp: MiddlewareHandler<AppEnv> = async (_c, next) => next();
function fixture() { const start = vi.fn(async () => ({ challenge_id: id, status: 'pending' as const, expires_at: '2026-10-01T12:00:00Z', requires_reauthentication: false, authorization_url: 'https://accounts.google.com/o/oauth2/v2/auth?state=opaque' })); const status = vi.fn(async () => ({ challenge_id: id, status: 'linked' as const, expires_at: '2026-10-01T12:00:00Z', requires_reauthentication: false })); const callback = vi.fn(async () => `lyra-mobile://auth/identity-link?challenge_id=${id}`); const auth = vi.fn<MiddlewareHandler<AppEnv>>(async (c, next) => { c.set('user', user); await next(); }); const app = new Hono<AppEnv>(); app.onError(errorHandler); app.route('/api/auth', createGoogleIdentityLinkRoutes({ service: { enabled: true, start, status, callback }, signInEnabled: true, authMiddleware: auth, rateLimitMiddleware: noOp, publicRateLimitMiddleware: noOp })); return { app, start, status, callback, auth }; }
describe('Google identity link routes', () => {
    it('public capabilities fail iOS closed without invoking user authentication', async () => { const f = fixture(); const r = await f.app.request('/api/auth/capabilities'); expect(await r.json()).toEqual({ google_sign_in: true, google_linking: true, google_ios: false }); expect(f.auth).not.toHaveBeenCalled(); expect(r.headers.get('cache-control')).toBe('no-store'); });
    it('authenticated start passes only validated platform/key and verified middleware proof', async () => { const f = fixture(); const r = await f.app.request('/api/auth/identity-links/google/start', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ platform: 'mobile', request_key: id }) }); expect(r.status).toBe(200); expect(f.start).toHaveBeenCalledWith(user, null, { platform: 'mobile', request_key: id }); expect(await r.json()).toMatchObject({ requires_reauthentication: false }); });
    it('rejects client-supplied identity, price, or redirect fields before service calls', async () => { const f = fixture(); const r = await f.app.request('/api/auth/identity-links/google/start', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ platform: 'mobile', request_key: id, redirect_uri: 'https://evil.invalid', nativeSubject: 'victim' }) }); expect(r.status).toBe(422); expect(f.start).not.toHaveBeenCalled(); });
    it('callback is public but returns only fixed validated service redirect without bearer tokens', async () => { const f = fixture(); const r = await f.app.request('/api/auth/identity-links/google/callback?state=opaque&code=private'); expect(r.status).toBe(303); expect(r.headers.get('location')).toBe(`lyra-mobile://auth/identity-link?challenge_id=${id}`); expect(r.headers.get('referrer-policy')).toBe('no-referrer'); expect(f.auth).not.toHaveBeenCalled(); });
    it('invalid callback never echoes query secrets', async () => { const f = fixture(); const r = await f.app.request('/api/auth/identity-links/google/callback?code=private'); expect(r.status).toBe(400); expect(await r.text()).not.toContain('private'); expect(f.callback).not.toHaveBeenCalled(); });
    it('receipt requires authentication and UUID scope', async () => { const f = fixture(); expect((await f.app.request(`/api/auth/identity-links/google/${id}`)).status).toBe(200); expect(f.status).toHaveBeenCalledWith(user, id); expect((await f.app.request('/api/auth/identity-links/google/not-uuid')).status).toBe(422); expect(f.status).toHaveBeenCalledTimes(1); });
});
