import { beforeAll, describe, expect, it, vi } from 'vitest';
import { createLocalJWKSet, exportJWK, generateKeyPair, SignJWT } from 'jose';
import { AdminGetUserCommand, AdminLinkProviderForUserCommand } from '@aws-sdk/client-cognito-identity-provider';
import { VerifiedGoogleIdentityLinkGateway } from '../../../../src/infrastructure/auth/GoogleIdentityLinkGateway.js';
let privateKey: Awaited<ReturnType<typeof generateKeyPair>>['privateKey'], jwks: ReturnType<typeof createLocalJWKSet>;
beforeAll(async () => { const pair = await generateKeyPair('RS256'); privateKey = pair.privateKey; jwks = createLocalJWKSet({ keys: [{ ...await exportJWK(pair.publicKey), kid: 'test' }] }); });
const config = { clientId: 'link-client', clientSecret: 'test-only-secret', redirectUri: 'https://api.example.com/api/auth/identity-links/google/callback', userPoolId: 'pool' };
async function token(overrides: Record<string, unknown> = {}) { return new SignJWT({ sub: 'google-sub', email: 'owner@example.com', email_verified: true, nonce: 'expected-nonce', ...overrides }).setProtectedHeader({ alg: 'RS256', kid: 'test' }).setIssuer('https://accounts.google.com').setAudience('link-client').setIssuedAt().setExpirationTime('5m').sign(privateKey); }
describe('Google identity proof and Cognito link gateway', () => {
    it('exchanges only at the official endpoint with PKCE and verifies signed proof', async () => { const fetcher = vi.fn(async (_url: string | URL | Request, _init?: RequestInit) => Response.json({ id_token: await token(), access_token: 'not-persisted' })); const g = new VerifiedGoogleIdentityLinkGateway(config, { send: vi.fn() }, fetcher as typeof fetch, jwks); expect(await g.exchangeCode({ code: 'code', verifier: 'verifier', nonce: 'expected-nonce' })).toEqual({ subject: 'google-sub', email: 'owner@example.com' }); expect(fetcher.mock.calls[0]?.[0]).toBe('https://oauth2.googleapis.com/token'); const init = fetcher.mock.calls[0]?.[1] as RequestInit; expect(init.redirect).toBe('error'); expect(new URLSearchParams(init.body as string).get('code_verifier')).toBe('verifier'); });
    it.each([{ email_verified: false }, { nonce: 'wrong' }, { sub: '' }, { azp: 'another-client' }])('rejects invalid Google proof %j', async (overrides) => { const g = new VerifiedGoogleIdentityLinkGateway(config, { send: vi.fn() }, (async () => Response.json({ id_token: await token(overrides) })) as typeof fetch, jwks); await expect(g.exchangeCode({ code: 'code', verifier: 'v', nonce: 'expected-nonce' })).rejects.toMatchObject({ code: 'UNAUTHORIZED' }); });
    it('rejects unsigned tokens and redacts token endpoint errors', async () => { const g = new VerifiedGoogleIdentityLinkGateway(config, { send: vi.fn() }, (async () => Response.json({ id_token: 'secret.invalid.raw' })) as typeof fetch, jwks); await expect(g.exchangeCode({ code: 'private-code', verifier: 'v', nonce: 'n' })).rejects.toThrow('Google identity proof could not be verified'); });
    it('reads the native profile rather than inferring login method from a identities claim', async () => { const send = vi.fn(async (_command: unknown, _options: unknown) => ({ Enabled: true, UserStatus: 'CONFIRMED', UserAttributes: [{ Name: 'sub', Value: 'native-sub' }, { Name: 'email', Value: 'owner@example.com' }, { Name: 'email_verified', Value: 'true' }, { Name: 'identities', Value: JSON.stringify([{ providerName: 'Google', userId: 'google-sub' }]) }] })); const g = new VerifiedGoogleIdentityLinkGateway(config, { send }); expect(await g.getNativeIdentity('native-name')).toMatchObject({ subject: 'native-sub', status: 'CONFIRMED', googleSubjects: ['google-sub'] }); expect(send.mock.calls[0]?.[0]).toBeInstanceOf(AdminGetUserCommand); });
    it('links verified Google subject only to the native Cognito username', async () => { const send = vi.fn(async (_command: unknown, _options: unknown) => ({})); const g = new VerifiedGoogleIdentityLinkGateway(config, { send }); await g.linkGoogleIdentity('native-name', 'google-sub'); const command = send.mock.calls[0]?.[0] as unknown as AdminLinkProviderForUserCommand; expect(command).toBeInstanceOf(AdminLinkProviderForUserCommand); expect(command.input).toEqual({ UserPoolId: 'pool', DestinationUser: { ProviderName: 'Cognito', ProviderAttributeValue: 'native-name' }, SourceUser: { ProviderName: 'Google', ProviderAttributeName: 'Cognito_Subject', ProviderAttributeValue: 'google-sub' } }); });
});
