import { describe, expect, it } from 'vitest';
import { resolveGoogleIdentityLinkConfig } from '../../../../src/infrastructure/auth/GoogleIdentityLinkConfig.js';
const config = { AWS_REGION: 'ap-northeast-1', AUTH_PROVIDER: 'cognito', GOOGLE_SIGN_IN_ENABLED: true, GOOGLE_IDENTITY_LINK_ENABLED: true, COGNITO_USER_POOL_ID: 'pool', COGNITO_CLIENT_ID: 'cognito-client', GOOGLE_COGNITO_IDP_CLIENT_ID: 'cognito-google-idp-client', GOOGLE_LINK_CLIENT_ID: 'google-client', GOOGLE_LINK_CLIENT_SECRET: 'test-only', GOOGLE_LINK_ENCRYPTION_SECRET: 's'.repeat(32), GOOGLE_LINK_REDIRECT_URI: 'https://api.example.com/api/auth/identity-links/google/callback', GOOGLE_LINK_WEB_RETURN_URI: 'https://app.example.com/auth/identity-link' };
describe('Google identity config', () => {
    it('default OFF requires no private configuration', () => expect(resolveGoogleIdentityLinkConfig({ AUTH_PROVIDER: 'supabase', GOOGLE_SIGN_IN_ENABLED: false, GOOGLE_IDENTITY_LINK_ENABLED: false })).toBeNull());
    it('requires complete dedicated config before enabling either authentication surface', () => { expect(() => resolveGoogleIdentityLinkConfig({ ...config, GOOGLE_IDENTITY_LINK_ENABLED: false })).toThrow(); expect(() => resolveGoogleIdentityLinkConfig({ ...config, GOOGLE_LINK_CLIENT_SECRET: undefined })).toThrow(); expect(() => resolveGoogleIdentityLinkConfig({ ...config, GOOGLE_LINK_CLIENT_ID: 'cognito-client' })).toThrow(); });
    it.each(['http://api.example.com/api/auth/identity-links/google/callback', 'https://api.example.com/other', 'https://api.example.com/api/auth/identity-links/google/callback?redirect=evil', 'https://name:password@api.example.com/api/auth/identity-links/google/callback'])('rejects an unsafe fixed redirect %s', (uri) => { expect(() => resolveGoogleIdentityLinkConfig({ ...config, GOOGLE_LINK_REDIRECT_URI: uri })).toThrow(); });
    it.each(['https://app.example.com/account', 'https://app.example.com/auth/identity-link?redirect=evil', 'https://app.example.com/auth/identity-link#fragment'])('rejects an unsupported Web return %s', (uri) => { expect(() => resolveGoogleIdentityLinkConfig({ ...config, GOOGLE_LINK_WEB_RETURN_URI: uri })).toThrow(); });
    it('accepts exact reviewed HTTPS configuration', () => expect(resolveGoogleIdentityLinkConfig(config)?.clientId).toBe('google-client'));
});
