import {describe,expect,it,vi} from 'vitest';
import {auditIdentitySubjects} from '../../../../src/services/auth/IdentitySubjectAudit.js';
import type {DatabaseClient,TransactionRunner} from '../../../../src/lib/db.js';
function database(users:{supabase_id:string;email:string}[]){const query=vi.fn(async(sql:string)=>({rows:sql.includes('SELECT u.')?users:[],rowCount:0,command:'SELECT',fields:[],oid:0}));const db={query,transaction:async<T>(work:(client:DatabaseClient)=>Promise<T>)=>work({query} as unknown as DatabaseClient)};return {db:db as unknown as DatabaseClient&TransactionRunner,query};}
describe('read-only subject migration audit',()=>{
 it('uses immutable subjects and returns aggregate counts only',async()=>{const {db,query}=database([{supabase_id:'native-1',email:'Owner@Example.com'}]);const report=await auditIdentitySubjects(db,async()=>({identities:[{subject:'native-1',email:'owner@example.com',enabled:true}],limitReached:false}));expect(report).toMatchObject({stable_subject_matches:1,missing_subjects:0,ready_for_subject_only_login:true});expect(JSON.stringify(report)).not.toContain('owner');expect(query.mock.calls[0][0]).toContain('READ ONLY');});
 it('matching email with a different subject blocks rather than generating a remap',async()=>{const {db}=database([{supabase_id:'old-sub',email:'owner@example.com'}]);const report=await auditIdentitySubjects(db,async()=>({identities:[{subject:'new-sub',email:'owner@example.com',enabled:true}],limitReached:false}));expect(report).toMatchObject({missing_subjects:1,ready_for_subject_only_login:false});expect(JSON.stringify(report)).not.toContain('new-sub');});
 it('limits and duplicate/malformed pool evidence cannot be called ready',async()=>{const {db}=database([{supabase_id:'a',email:'a@example.com'}]);const report=await auditIdentitySubjects(db,async()=>({identities:[{subject:'a',email:null,enabled:false},{subject:'a',email:null,enabled:false},{subject:'',email:null,enabled:true}],limitReached:true}));expect(report).toMatchObject({duplicate_pool_subjects:1,malformed_pool_identities:1,inspection_limit_reached:true,ready_for_subject_only_login:false});});
 it('does not retrieve pool identities if the database inspection itself was truncated',async()=>{const {db}=database([{supabase_id:'a',email:'a@example.com'},{supabase_id:'b',email:'b@example.com'}]);const read=vi.fn();expect((await auditIdentitySubjects(db,read,1)).inspection_limit_reached).toBe(true);expect(read).not.toHaveBeenCalled();});
});
